version: '3.3'
services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/Financial_Academy/static
      - media_volume:/home/Financial_Academy/media
      - /etc/letsencrypt/live/practicumkg.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/practicumkg.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --workers=4 congig.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/Financial_Academy/static
      - media_volume:/home/Financial_Academy/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
