version: '3.8'
services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/Financial_Academy/staticfiles
      - media_volume:/home/Financial_Academy/mediafiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
  web:
    build:
      context: ./app
      dockerfile: Dockerfileprod
    command: gunicorn --workers=4 site_project.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/Financial_Academy/staticfiles
      - media_volume:/home/Financial_Academy/mediafiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5451:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
