# Generated by Django 4.2.3 on 2023-07-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True, verbose_name='TikTok')),
                ('whatsapp', models.URLField(blank=True, max_length=100, null=True, verbose_name='WhatsApp')),
                ('telegram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер тел.')),
                ('address', models.URLField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='courses/', verbose_name='Фото')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Длительность (в неделях)')),
                ('number_of_exercises', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество уроков')),
                ('number_of_students', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество студентов')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена')),
                ('visiting_days', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дни занятий (Пн, Ср, Пт)')),
                ('visiting_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время занятий (12:00-13:00)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображаемость')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_services/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('experience', models.TextField(blank=True, max_length=500, null=True, verbose_name='Опыт')),
                ('achievements', models.TextField(blank=True, max_length=500, null=True, verbose_name='Награды')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фото')),
                ('courses', models.ManyToManyField(related_name='teachers', to='academy.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeachersImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='teachers_images/', verbose_name='Изображения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Изображения преподавателя',
                'verbose_name_plural': 'Изображения преподавателей',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер тел.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='news/', verbose_name='Изображения')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображения новости',
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
        migrations.CreateModel(
            name='CourseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='courses/', verbose_name='Изображения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Изображения курса',
                'verbose_name_plural': 'Изображения курсов',
            },
        ),
    ]
