# Generated by Django 4.2.3 on 2023-07-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('instagramm', models.URLField(max_length=100, verbose_name='instagramm')),
                ('whatsapp', models.URLField(max_length=100, verbose_name='whatsapp')),
                ('telegram', models.URLField(max_length=100, verbose_name='telegram')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('address', models.URLField(max_length=100, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('number_of_exercises', models.PositiveIntegerField(verbose_name='number of exercises')),
                ('number_of_students', models.PositiveIntegerField(verbose_name='number of students')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('visiting_days', models.CharField(max_length=100, verbose_name='visiting days')),
                ('visiting_time', models.CharField(max_length=100, verbose_name='visiting time')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('experience', models.TextField(max_length=500, verbose_name='experience')),
                ('achievements', models.TextField(max_length=500, verbose_name='achievements')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='photo')),
                ('courses', models.ManyToManyField(related_name='teachers', to='academy.course', verbose_name='courses')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeachersImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='teachers/', verbose_name='images')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Teacher image',
                'verbose_name_plural': 'Teacher images',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='news/', verbose_name='images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'News image',
                'verbose_name_plural': 'News images',
            },
        ),
        migrations.CreateModel(
            name='CourseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='courses/', verbose_name='images')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Course image',
                'verbose_name_plural': 'Course images',
            },
        ),
    ]
