# Generated by Django 4.2.3 on 2023-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт'),
        ),
    ]
