# Generated by Django 4.2.3 on 2023-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_rename_instagramm_contact_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(max_length=100, verbose_name='instagram'),
        ),
    ]
