# Generated by Django 4.2.3 on 2023-07-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_contact_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersimages',
            name='images',
            field=models.ImageField(upload_to='teachers_images/', verbose_name='images'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
