# Generated by Django 4.2.3 on 2023-07-12 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_teachersimages_images_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 13, 0, 18, 96633, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
