# Generated by Django 4.2.3 on 2023-07-12 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 12, 14, 51, 31, 854331, tzinfo=datetime.timezone.utc), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 14, 51, 31, 852007, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='StocksImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='stocks/', verbose_name='images')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.stocks', verbose_name='Stocks')),
            ],
            options={
                'verbose_name': 'Stock image',
                'verbose_name_plural': 'Stocks images',
            },
        ),
    ]
