# Generated by Django 4.2.3 on 2023-07-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_news_date_alter_stocks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 11, 22, 2, 924205, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 11, 22, 2, 926630, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
