# Generated by Django 4.2.3 on 2023-07-13 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_news_date_alter_stocks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 14, 27, 51, 154627, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 14, 27, 51, 155809, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
