# Generated by Django 4.2.3 on 2023-07-14 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_aboutus_alter_news_date_alter_stocks_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseimages',
            options={'verbose_name': 'Изображения курса', 'verbose_name_plural': 'Изображения курсов'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsimages',
            options={'verbose_name': 'Изображения новости', 'verbose_name_plural': 'Изображения новостей'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='stocksimages',
            options={'verbose_name': 'Изображения акции', 'verbose_name_plural': 'Изображения акции'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teachersimages',
            options={'verbose_name': 'Изображения преподавателя', 'verbose_name_plural': 'Изображения преподавателей'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.URLField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер тел.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.URLField(max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.URLField(max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Длительность (в неделях)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображаемость'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_exercises',
            field=models.PositiveIntegerField(verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_of_students',
            field=models.PositiveIntegerField(verbose_name='Количество студентов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visiting_days',
            field=models.CharField(max_length=100, verbose_name='Дни занятий (Пн, Ср, Пт)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visiting_time',
            field=models.CharField(max_length=100, verbose_name='Время занятий (12:00-13:00)'),
        ),
        migrations.AlterField(
            model_name='courseimages',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseimages',
            name='images',
            field=models.ImageField(upload_to='courses/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 6, 46, 53, 981133, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='images',
            field=models.ImageField(upload_to='news/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='request',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='request',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Номер тел.'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 6, 46, 53, 983081, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='stocksimages',
            name='images',
            field=models.ImageField(upload_to='stocks/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='stocksimages',
            name='stocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.stocks', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='achievements',
            field=models.TextField(max_length=500, verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='academy.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(max_length=500, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teachersimages',
            name='images',
            field=models.ImageField(upload_to='teachers_images/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='teachersimages',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.teacher', verbose_name='Преподаватель'),
        ),
    ]
