# Generated by Django 4.2.3 on 2023-07-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_alter_news_date_alter_stocks_date'),
        ('academy', '0010_alter_contact_options_alter_course_options_and_more'),
    ]

    operations = [
    ]
