# Generated by Django 4.2.3 on 2023-07-14 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_merge_20230714_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 6, 52, 32, 151190, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 6, 52, 32, 153185, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
