# Generated by Django 4.2.3 on 2023-07-14 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_contact_tiktok_alter_news_date_alter_stocks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 14, 47, 3, 613124, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 14, 47, 3, 615277, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
