# Generated by Django 4.2.3 on 2023-07-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_course_duration_alter_news_date_and_more'),
        ('academy', '0014_alter_news_date_alter_stocks_date'),
    ]

    operations = [
    ]
